#pragma config(Sensor, S1,     light,          sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat(forever)
	{
		// display the value of the light sensor on screen //
		displayBigTextLine(0, "Light: %d", SensorValue[light]);

		// wait 100 ms before updating //
		sleep(100);
	}
}
