#pragma config(Sensor, S1,     light,          sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(SensorValue[light]>52.5){

motor[motorA]=35;
motor[motorD]=35;

}
motor[motorA]=0;
motor[motorD]=0;
}
