#pragma config(Sensor, S1,     touch1,         sensorEV3_Touch)
#pragma config(Sensor, S2,     touch2,         sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	repeat(forever)
	{

		if (SensorValue[touch1] == 1)
		{
			motor[motorA] = 50;
			motor[motorB] = 0;
			} else {
			if (SensorValue[touch2] == 1)
			{
				motor[motorA] = 0;
				motor[motorB] = 50;
				} else {
				motor[motorA] = 0;
				motor[motorB] = 0;
			}
		}
	}
}
