#pragma config(Sensor, S1,     light1,         sensorEV3_Color)
#pragma config(Sensor, S2,     light2,         sensorEV3_Color)
#pragma config(Sensor, S3,     touch,          sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	clearTimer(T1);

	while (time1[T1] < 11000)
	{
		if ((SensorValue[light1] >52.5) && (SensorValue[light2] >52.5))
		{
			motor[motorA] = 25;
			motor[motorD] = 25;
			}	else {
			if (SensorValue[light1] > 52.5)
			{
				motor[motorA] = 25;
				motor[motorD] = 0;
				} else {
				if (SensorValue[light2] > 52.5)
				{
					motor[motorA] = 0;
					motor[motorD] = 25;
					} else {
					motor[motorA] = 0;
					motor[motorD] = 0;
				}
			}
		}
	}

	motor[motorA] = 0;
	motor[motorD] = 0;

	sleep(2000);

	resetMotorEncoder(motorA);
	resetMotorEncoder(motorD);
	setMotorTarget(motorA, 150, -25);
	setMotorTarget(motorD, -150, -25);
	waitUntilMotorStop(motorD);
	sleep(1000);

	repeat(3)
	{
		while(SensorValue[touch] == 0)
		{
			motor[motorA] = 25;
			motor[motorD] = 25;
		}
		motor[motorA] = 0;
		motor[motorD] = 0;

		resetMotorEncoder(motorA);
		resetMotorEncoder(motorD);
		setMotorTarget(motorA, -100, 25);
		setMotorTarget(motorD, -100, 25);
		waitUntilMotorStop(motorD);
		sleep(1000);


		resetMotorEncoder(motorA);
		resetMotorEncoder(motorD);
		setMotorTarget(motorA, -150, -25);
		setMotorTarget(motorD, 150, -25);
		waitUntilMotorStop(motorD);
		sleep(1000);

	}
}
